kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
    volumes:
      - name: cache
        path: /tmp/cache:/cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install
    image: node:carbon
    when:
      event: [push, pull_request]
      branch: master
    commands:
      - yarn

  - name: test
    image: node:carbon
    when:
      event: [push, pull_request]
      branch: master
    commands:
      - yarn test

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
    volumes:
      - name: cache
        path: /tmp/cache:/cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    when:
      event: push
      branch: master
      status: success
    settings:
      host: nansen.online.ntnu.no
      key:
        from_secret: ssh_key
      command_timeout: 4m
      script:
        - /srv/www/notiwall/deploy.sh
