kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
    settings:
      restore: true
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache

  - name: test
    image: node:carbon
    when:
      event: [push, pull_request]
      branch: master
    commands:
      - yarn
      - yarn test

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    when:
      event: push
      branch: master
      status: success
    settings:
      host: nansen.online.ntnu.no
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - /srv/www/notiwall/deploy.sh

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
    settings:
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache
      rebuild: true
