pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
      branch: master
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  test:
    image: node:carbon
    when:
      event: [push, pull_request]
      branch: master
    commands:
      - yarn
      - yarn test
  deploy:
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    host: nansen.online.ntnu.no
    port: 22
    username: root
    key: ${SSH_KEY}
    command_timeout: 2m
    when:
      event: push
      branch: master
      status: success
    script:
      - /srv/www/notiwall/deploy.sh
  rebuild-cache:
    image: drillster/drone-volume-cache
    when:
      event: [push, pull_request]
      branch: master
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
